//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyDean.FareLiz.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyDean.FareLiz.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,&quot;Goroka&quot;,&quot;Goroka&quot;,&quot;Papua New Guinea&quot;,&quot;GKA&quot;,&quot;AYGA&quot;,-6.081689,145.391881,5282,10,&quot;U&quot;
        ///2,&quot;Madang&quot;,&quot;Madang&quot;,&quot;Papua New Guinea&quot;,&quot;MAG&quot;,&quot;AYMD&quot;,-5.207083,145.7887,20,10,&quot;U&quot;
        ///3,&quot;Mount Hagen&quot;,&quot;Mount Hagen&quot;,&quot;Papua New Guinea&quot;,&quot;HGU&quot;,&quot;AYMH&quot;,-5.826789,144.295861,5388,10,&quot;U&quot;
        ///4,&quot;Nadzab&quot;,&quot;Nadzab&quot;,&quot;Papua New Guinea&quot;,&quot;LAE&quot;,&quot;AYNZ&quot;,-6.569828,146.726242,239,10,&quot;U&quot;
        ///5,&quot;Port Moresby Jacksons Intl&quot;,&quot;Port Moresby&quot;,&quot;Papua New Guinea&quot;,&quot;POM&quot;,&quot;AYPY&quot;,-9.443383,147.22005,146,10,&quot;U&quot;
        ///6,&quot;Wewak Intl&quot;,&quot;Wewak&quot;,&quot;Papua New Guinea&quot;,&quot;WWK&quot;,&quot;AYWK&quot;,-3. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Airports {
            get {
                return ResourceManager.GetString("Airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon SkyDeanBlackIcon {
            get {
                object obj = ResourceManager.GetObject("SkyDeanBlackIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
